\documentclass{article}

\begin{document}
\author{Adam Rydelek}
\title{Very basic .Rnw document}
\maketitle
\section{First section}
\subsection{Basic text}

Just a few words in here.

\section{Second section}
\subsection{R code}

<<>>=
#Basic function
print("Hello")
@

\section{Image section}
\subsection{Random photo}

\includegraphics{cat.jpeg}

\section{Plot section}
\subsection{Random plot}

<<>>=
#Basic plot
x<-seq(0,10,by = 0.1)
y <- rnorm(n = length(x))
plot(y~x)
@


\end{document}